// Code generated by MockGen. DO NOT EDIT.
// Source: stream.go
//
// Generated by this command:
//
//	mockgen -source=stream.go -destination=mock_stream.go -package=koro
//

// Package koro is a generated GoMock package.
package koro

import (
	context "context"
	reflect "reflect"

	dynamodbstreams "github.com/aws/aws-sdk-go-v2/service/dynamodbstreams"
	gomock "go.uber.org/mock/gomock"
)

// MockDynamoDBStreamer is a mock of DynamoDBStreamer interface.
type MockDynamoDBStreamer struct {
	ctrl     *gomock.Controller
	recorder *MockDynamoDBStreamerMockRecorder
}

// MockDynamoDBStreamerMockRecorder is the mock recorder for MockDynamoDBStreamer.
type MockDynamoDBStreamerMockRecorder struct {
	mock *MockDynamoDBStreamer
}

// NewMockDynamoDBStreamer creates a new mock instance.
func NewMockDynamoDBStreamer(ctrl *gomock.Controller) *MockDynamoDBStreamer {
	mock := &MockDynamoDBStreamer{ctrl: ctrl}
	mock.recorder = &MockDynamoDBStreamerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDynamoDBStreamer) EXPECT() *MockDynamoDBStreamerMockRecorder {
	return m.recorder
}

// DescribeStream mocks base method.
func (m *MockDynamoDBStreamer) DescribeStream(arg0 context.Context, arg1 *dynamodbstreams.DescribeStreamInput, arg2 ...func(*dynamodbstreams.Options)) (*dynamodbstreams.DescribeStreamOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DescribeStream", varargs...)
	ret0, _ := ret[0].(*dynamodbstreams.DescribeStreamOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DescribeStream indicates an expected call of DescribeStream.
func (mr *MockDynamoDBStreamerMockRecorder) DescribeStream(arg0, arg1 any, arg2 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DescribeStream", reflect.TypeOf((*MockDynamoDBStreamer)(nil).DescribeStream), varargs...)
}

// GetRecords mocks base method.
func (m *MockDynamoDBStreamer) GetRecords(arg0 context.Context, arg1 *dynamodbstreams.GetRecordsInput, arg2 ...func(*dynamodbstreams.Options)) (*dynamodbstreams.GetRecordsOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetRecords", varargs...)
	ret0, _ := ret[0].(*dynamodbstreams.GetRecordsOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRecords indicates an expected call of GetRecords.
func (mr *MockDynamoDBStreamerMockRecorder) GetRecords(arg0, arg1 any, arg2 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRecords", reflect.TypeOf((*MockDynamoDBStreamer)(nil).GetRecords), varargs...)
}

// GetShardIterator mocks base method.
func (m *MockDynamoDBStreamer) GetShardIterator(arg0 context.Context, arg1 *dynamodbstreams.GetShardIteratorInput, arg2 ...func(*dynamodbstreams.Options)) (*dynamodbstreams.GetShardIteratorOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetShardIterator", varargs...)
	ret0, _ := ret[0].(*dynamodbstreams.GetShardIteratorOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetShardIterator indicates an expected call of GetShardIterator.
func (mr *MockDynamoDBStreamerMockRecorder) GetShardIterator(arg0, arg1 any, arg2 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetShardIterator", reflect.TypeOf((*MockDynamoDBStreamer)(nil).GetShardIterator), varargs...)
}

// ListStreams mocks base method.
func (m *MockDynamoDBStreamer) ListStreams(arg0 context.Context, arg1 *dynamodbstreams.ListStreamsInput, arg2 ...func(*dynamodbstreams.Options)) (*dynamodbstreams.ListStreamsOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListStreams", varargs...)
	ret0, _ := ret[0].(*dynamodbstreams.ListStreamsOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListStreams indicates an expected call of ListStreams.
func (mr *MockDynamoDBStreamerMockRecorder) ListStreams(arg0, arg1 any, arg2 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListStreams", reflect.TypeOf((*MockDynamoDBStreamer)(nil).ListStreams), varargs...)
}
