name: Go

on:
  - push
  - pull_request

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Setup DynamoDB Local
      uses: rrainn/dynamodb-action@v2.0.0
      with:
        port: 18000
        cors: '*'

    - name: Set up Go 1.17
      uses: actions/setup-go@v1
      with:
        go-version: ^1.17.x
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: |
        go get -v -t -d ./...

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v -cover ./...
      env:
        DYNAMODB_ADDR: 'http://127.0.0.1:18000'
